import { readFile, writeFile } from 'node:fs/promises'

const sourcePath = new URL('../src/assets/xiaohei-night.webp', import.meta.url)
const targetPath = new URL('../src/generated-keyart.ts', import.meta.url)
const source = await readFile(sourcePath)
const dataUrl = `data:image/webp;base64,${source.toString('base64')}`

await writeFile(
  targetPath,
  `/** Generated by scripts/embed-assets.mjs. */\nexport const XIAOHEI_KEY_ART = ${JSON.stringify(dataUrl)}\n`,
  'utf8',
)
