import { readFile, writeFile } from 'node:fs/promises'

const targetPath = new URL('../src/generated-keyart.ts', import.meta.url)
const identityTargetPath = new URL('../src/generated-identity.ts', import.meta.url)
const loadingTargetPath = new URL('../src/generated-loading-assets.ts', import.meta.url)
const avatarModelTargetPath = new URL('../src/generated-avatar-model.ts', import.meta.url)
const characterAssets = [
  ['XIAOHEI_IDLE_SHEET', 'xiaohei-idle.webp'],
  ['XIAOHEI_IDLE_BLINK', 'xiaohei-idle-blink-v1.webp'],
  ['XIAOHEI_IDLE_EYE_BASE', 'xiaohei-idle-eye-base-v1.webp'],
  ['XIAOHEI_IDLE_EAR_LEFT', 'xiaohei-idle-ear-left-v1.webp'],
  ['XIAOHEI_IDLE_EAR_RIGHT', 'xiaohei-idle-ear-right-v1.webp'],
  ['XIAOHEI_IDLE_TAIL', 'xiaohei-idle-tail-v1.webp'],
  ['XIAOHEI_THINKING', 'xiaohei-thinking-canonical-v12.webp'],
  ['XIAOHEI_STREAMING', 'xiaohei-streaming-tailwrite-v1.webp'],
  ['XIAOHEI_TOOL', 'xiaohei-tool-canonical-v2.webp'],
  ['XIAOHEI_WAITING', 'xiaohei-waiting-canonical-v2.webp'],
  ['XIAOHEI_COMPLETE', 'xiaohei-complete-canonical-v2.webp'],
  ['XIAOHEI_ERROR', 'xiaohei-error-canonical-v2.webp'],
  ['XIAOHEI_HEIXIU_OPEN', 'heixiu-open-v1.webp'],
  ['XIAOHEI_HEIXIU_BLINK', 'heixiu-blink-v1.webp'],
]
const embeddedCharacters = await Promise.all(characterAssets.map(async ([name, filename]) => {
  const assetPath = new URL(`../src/assets/character/${filename}`, import.meta.url)
  const asset = await readFile(assetPath)
  return `export const ${name}: string = ${JSON.stringify(`data:image/webp;base64,${asset.toString('base64')}`)}`
}))
const loadingAssets = [
  ['XIAOHEI_LOADING_HEIXIU_OPEN', 'heixiu-open-v1.webp'],
  ['XIAOHEI_LOADING_HEIXIU_BLINK', 'heixiu-blink-v1.webp'],
]
const embeddedLoadingAssets = await Promise.all(loadingAssets.map(async ([name, filename]) => {
  const assetPath = new URL(`../src/assets/character/${filename}`, import.meta.url)
  const asset = await readFile(assetPath)
  return `export const ${name}: string = ${JSON.stringify(`data:image/webp;base64,${asset.toString('base64')}`)}`
}))
const identityAssets = [
  ['XIAOHEI_BRAND_AVATAR', 'xiaohei-brand-head-v2.webp'],
  ['XIAOHEI_IDENTITY_CHARM', 'luoxiaohei-tail-charm-v1.webp'],
  ['XIAOHEI_IDENTITY_SPACE_RING', 'luoxiaohei-space-ring-v1.webp'],
  ['XIAOHEI_IDENTITY_CAT_TAG', 'luoxiaohei-cat-mouth-tag-v1.webp'],
]
const embeddedIdentity = await Promise.all(identityAssets.map(async ([name, filename]) => {
  const assetPath = new URL(`../src/assets/identity/${filename}`, import.meta.url)
  const asset = await readFile(assetPath)
  return `export const ${name}: string = ${JSON.stringify(`data:image/webp;base64,${asset.toString('base64')}`)}`
}))
const avatarModelAssets = [
  ['XIAOHEI_AVATAR_OPEN', 'xiaohei-avatar-open-v1.webp'],
  ['XIAOHEI_AVATAR_BLINK', 'xiaohei-avatar-blink-v1.webp'],
  ['XIAOHEI_AVATAR_CLIMB', 'xiaohei-avatar-climb-v1.webp'],
  ['XIAOHEI_AVATAR_JUMP', 'xiaohei-avatar-jump-v1.webp'],
]
const embeddedAvatarModel = await Promise.all(avatarModelAssets.map(async ([name, filename]) => {
  const assetPath = new URL(`../src/assets/model/${filename}`, import.meta.url)
  const asset = await readFile(assetPath)
  return `export const ${name}: string = ${JSON.stringify(`data:image/webp;base64,${asset.toString('base64')}`)}`
}))

await writeFile(
  targetPath,
  [
    '/** Generated by scripts/embed-assets.mjs. */',
    ...embeddedCharacters,
    '',
  ].join('\n'),
  'utf8',
)

await writeFile(
  identityTargetPath,
  [
    '/** Generated by scripts/embed-assets.mjs. */',
    ...embeddedIdentity,
    '',
  ].join('\n'),
  'utf8',
)

await writeFile(
  loadingTargetPath,
  [
    '/** Generated by scripts/embed-assets.mjs for the pre-plugin Host bootstrap. */',
    ...embeddedLoadingAssets,
    '',
  ].join('\n'),
  'utf8',
)

await writeFile(
  avatarModelTargetPath,
  [
    '/** Generated by scripts/embed-assets.mjs for the in-scene Xiaohei model. */',
    ...embeddedAvatarModel,
    '',
  ].join('\n'),
  'utf8',
)
