import { readFile, writeFile } from 'node:fs/promises'

const sourcePath = new URL('../src/assets/xiaohei-night-balanced.webp', import.meta.url)
const targetPath = new URL('../src/generated-keyart.ts', import.meta.url)
const source = await readFile(sourcePath)
const dataUrl = `data:image/webp;base64,${source.toString('base64')}`
const characterAssets = [
  ['XIAOHEI_IDLE_SHEET', 'xiaohei-idle.webp'],
  ['XIAOHEI_ENERGY', 'xiaohei-energy.webp'],
  ['XIAOHEI_STREAMING', 'xiaohei-streaming.webp'],
  ['XIAOHEI_TOOL', 'xiaohei-tool.webp'],
  ['XIAOHEI_WAITING', 'xiaohei-waiting.webp'],
  ['XIAOHEI_COMPLETE', 'xiaohei-complete.webp'],
  ['XIAOHEI_ERROR', 'xiaohei-error.webp'],
]
const embeddedCharacters = await Promise.all(characterAssets.map(async ([name, filename]) => {
  const assetPath = new URL(`../src/assets/character/${filename}`, import.meta.url)
  const asset = await readFile(assetPath)
  return `export const ${name} = ${JSON.stringify(`data:image/webp;base64,${asset.toString('base64')}`)}`
}))

await writeFile(
  targetPath,
  [
    '/** Generated by scripts/embed-assets.mjs. */',
    `export const XIAOHEI_KEY_ART = ${JSON.stringify(dataUrl)}`,
    ...embeddedCharacters,
    '',
  ].join('\n'),
  'utf8',
)
