import type {
  ThemeDefinition,
  ThemeTokenOverrides,
  ThemeTokens,
} from '@deepseek-ai/dsh-client-ui-theme/client'

/** Stable ids retained for consumers that inspect the two Xiaohei palettes. */
export const XIAOHEI_DAWN_THEME_ID = 'xiaohei-dawn'
export const XIAOHEI_NIGHT_THEME_ID = 'xiaohei-night'

const DAWN_TOKENS: ThemeTokens = {
  '--dsw-alias-bg-base': 'rgb(239 243 238 / 18%)',
  '--dsw-alias-bg-layer-1': 'rgb(249 251 248 / 72%)',
  '--dsw-alias-bg-layer-2': 'rgb(247 250 247 / 88%)',
  '--dsw-alias-bg-layer-3': 'rgb(242 247 243 / 95%)',
  '--dsw-alias-bg-overlay': '#F7FAF7',
  '--dsw-alias-bg-module-platform': 'rgb(246 249 246 / 84%)',
  '--dsw-alias-bg-multi-select': '#E8F0EA',
  '--dsw-alias-bg-skeleton': 'rgb(47 133 118 / 10%)',

  '--dsw-alias-border-inverted2': 'rgb(36 94 81 / 6%)',
  '--dsw-alias-border-inverted': 'rgb(36 94 81 / 9%)',
  '--dsw-alias-border-l1': 'rgb(36 94 81 / 9%)',
  '--dsw-alias-border-l2-darkmode-thin': 'rgb(36 94 81 / 12%)',
  '--dsw-alias-border-l2': 'rgb(36 94 81 / 15%)',
  '--dsw-alias-border-l3': 'rgb(36 94 81 / 22%)',
  '--dsw-alias-border-l4': 'rgb(36 94 81 / 31%)',

  '--dsw-alias-brand-primary': '#2F8576',
  '--dsw-alias-brand-primary-invert': '#F7FBF8',
  '--dsw-alias-brand-primary-new-colorprimary-new-color': '#2F8576',
  '--dsw-alias-brand-text': '#276E62',
  '--dsw-alias-button-contrast-fill': '#25332F',
  '--dsw-alias-button-primary-fill': '#2D806F',
  '--dsw-alias-button-primary-hover': '#276F61',
  '--dsw-alias-button-primary-dimmed': '#9BC1B7',
  '--dsw-alias-button-elevated-fill': '#F6F9F6',
  '--dsw-alias-button-floating-fill': '#EDF3EE',
  '--dsw-alias-button-floating-hover': '#E2ECE5',
  '--dsw-alias-button-ghost-active-border': '#78AA9E',
  '--dsw-alias-button-ghost-active-fill': 'rgb(47 133 118 / 12%)',
  '--dsw-alias-button-ghost-active-hover': 'rgb(47 133 118 / 18%)',
  '--dsw-alias-button-info-fill': '#2F8576',
  '--dsw-alias-button-info-hover': '#287566',

  '--dsw-alias-interactive-bg-active': 'rgb(47 133 118 / 15%)',
  '--dsw-alias-interactive-bg-hover-accent': 'rgb(47 133 118 / 18%)',
  '--dsw-alias-interactive-bg-hover-solid': '#E8F0EA',
  '--dsw-alias-interactive-bg-hover': 'rgb(47 133 118 / 9%)',

  '--dsw-alias-label-primary': '#1E2B28',
  '--dsw-alias-label-primary-bluish': '#1E2B28',
  '--dsw-alias-label-primary-dimmed': '#34443F',
  '--dsw-alias-label-primary-foreground': '#FFFFFF',
  '--dsw-alias-label-primary-inverted': '#F7FAF7',
  '--dsw-alias-label-secondary': '#52645F',
  '--dsw-alias-label-tertiary': '#60726C',
  '--dsw-alias-label-caption': '#60716B',
  '--dsw-alias-label-dimmed': '#899791',

  '--dsw-alias-markdown-citation': '#E4EDE7',
  '--dsw-alias-markdown-code-block-banner': '#E7EEE9',
  '--dsw-alias-markdown-code-block': '#F2F6F3',
  '--dsw-alias-markdown-code-segment-selected': '#DDE8E1',
  '--dsw-alias-markdown-code-segment-unselected': '#EDF3EF',
  '--dsw-alias-markdown-inline-code': '#E8F0EA',
  '--dsw-alias-markdown-placeholder': '#EDF3EF',
  '--dsw-alias-markdown-tag': '#E4EDE7',

  '--dsw-alias-scrollbar-bg-l1': '#C7D4CD',
  '--dsw-alias-scrollbar-bg-l2': '#B7C8BF',
  '--dsw-alias-scrollbar-hover-l1': '#A5BAB0',
  '--dsw-alias-scrollbar-hover-l2': '#91AA9F',

  '--dsw-alias-state-error-primary': '#B44952',
  '--dsw-alias-state-error-secondary': '#C65D65',
  '--dsw-alias-state-business-primary': '#2F8576',
  '--dsw-alias-state-business-tertiary': '#DDEBE6',
  '--dsw-alias-state-success-primary': '#2F7B52',
  '--dsw-alias-state-success-secondary': '#438D65',
  '--dsw-alias-state-success-tertiary': '#DCEBDF',
  '--dsw-alias-state-warn-label': '#8A5B1C',
  '--dsw-alias-state-warn-primary': '#9A6720',
  '--dsw-alias-state-warn-secondary': '#AD7A34',
  '--dsw-alias-state-warn-tertiary': '#F3E8D2',

  '--dsw-alias-toast-bg': '#F7FAF7',
  '--dsw-alias-tooltip-bg': '#25332F',
  '--dsw-specific-bubble': 'rgb(249 251 248 / 94%)',
  '--dsw-specific-bubble-highlight': '#E8F0EA',
  '--dsw-specific-input-major': 'rgb(250 252 249 / 94%)',
  '--dsw-specific-login-input': 'rgb(247 250 247 / 94%)',
  '--dsw-specific-menu': '#F4F8F4',
  '--dsw-specific-selector': '#E8F0EA',
  '--dsw-specific-sidebar-fill': 'rgb(239 245 240 / 76%)',
  '--dsw-specific-sidebar-nav-item-active-accent': '#CFE1DA',
  '--dsw-specific-sidebar-nav-item-active': '#E3EDE7',
  '--dsw-specific-sidebar-nav-item-hover': '#EBF2ED',
  '--dsw-specific-tip': '#E8F0EA',
}

const NIGHT_TOKENS: ThemeTokens = {
  '--dsw-alias-bg-base': 'rgb(8 20 24 / 14%)',
  '--dsw-alias-bg-layer-1': 'rgb(11 24 27 / 70%)',
  '--dsw-alias-bg-layer-2': 'rgb(15 32 34 / 84%)',
  '--dsw-alias-bg-layer-3': 'rgb(20 42 42 / 92%)',
  '--dsw-alias-bg-overlay': '#193333',
  '--dsw-alias-bg-module-platform': 'rgb(10 22 25 / 76%)',
  '--dsw-alias-bg-multi-select': '#142A2A',
  '--dsw-alias-bg-skeleton': 'rgb(101 209 190 / 9%)',

  '--dsw-alias-border-inverted2': 'rgb(113 221 201 / 7%)',
  '--dsw-alias-border-inverted': 'rgb(113 221 201 / 10%)',
  '--dsw-alias-border-l1': 'rgb(113 221 201 / 8%)',
  '--dsw-alias-border-l2-darkmode-thin': 'rgb(113 221 201 / 11%)',
  '--dsw-alias-border-l2': 'rgb(113 221 201 / 15%)',
  '--dsw-alias-border-l3': 'rgb(113 221 201 / 23%)',
  '--dsw-alias-border-l4': 'rgb(113 221 201 / 32%)',

  '--dsw-alias-brand-primary': '#65D1BE',
  '--dsw-alias-brand-primary-invert': '#07221E',
  '--dsw-alias-brand-primary-new-colorprimary-new-color': '#65D1BE',
  '--dsw-alias-brand-text': '#78DDCB',
  '--dsw-alias-button-contrast-fill': '#E7F3F0',
  '--dsw-alias-button-primary-fill': '#65D1BE',
  '--dsw-alias-button-primary-hover': '#7BE0CE',
  '--dsw-alias-button-primary-dimmed': '#356F65',
  '--dsw-alias-button-elevated-fill': '#193333',
  '--dsw-alias-button-floating-fill': '#142A2A',
  '--dsw-alias-button-floating-hover': '#1E3D3B',
  '--dsw-alias-button-ghost-active-border': '#356F65',
  '--dsw-alias-button-ghost-active-fill': 'rgb(101 209 190 / 16%)',
  '--dsw-alias-button-ghost-active-hover': 'rgb(101 209 190 / 23%)',
  '--dsw-alias-button-info-fill': '#65D1BE',
  '--dsw-alias-button-info-hover': '#7BE0CE',

  '--dsw-alias-interactive-bg-active': 'rgb(101 209 190 / 18%)',
  '--dsw-alias-interactive-bg-hover-accent': 'rgb(101 209 190 / 24%)',
  '--dsw-alias-interactive-bg-hover-solid': '#193333',
  '--dsw-alias-interactive-bg-hover': 'rgb(101 209 190 / 10%)',

  '--dsw-alias-label-primary': '#E7F3F0',
  '--dsw-alias-label-primary-bluish': '#E7F3F0',
  '--dsw-alias-label-primary-dimmed': '#CFDFDB',
  '--dsw-alias-label-primary-foreground': '#07221E',
  '--dsw-alias-label-primary-inverted': '#193333',
  '--dsw-alias-label-secondary': '#B9D0CB',
  '--dsw-alias-label-tertiary': '#91AAA5',
  '--dsw-alias-label-caption': '#809994',
  '--dsw-alias-label-dimmed': '#617773',

  '--dsw-alias-markdown-citation': '#193333',
  '--dsw-alias-markdown-code-block-banner': '#0F2022',
  '--dsw-alias-markdown-code-block': '#071114',
  '--dsw-alias-markdown-code-segment-selected': '#193333',
  '--dsw-alias-markdown-code-segment-unselected': '#0B181B',
  '--dsw-alias-markdown-inline-code': '#142A2A',
  '--dsw-alias-markdown-placeholder': '#0F2022',
  '--dsw-alias-markdown-tag': '#142A2A',

  '--dsw-alias-scrollbar-bg-l1': '#294A47',
  '--dsw-alias-scrollbar-bg-l2': '#35605B',
  '--dsw-alias-scrollbar-hover-l1': '#42746D',
  '--dsw-alias-scrollbar-hover-l2': '#4E877E',

  '--dsw-alias-state-error-primary': '#FF7D86',
  '--dsw-alias-state-error-secondary': '#FF9AA1',
  '--dsw-alias-state-business-primary': '#65D1BE',
  '--dsw-alias-state-business-tertiary': '#193333',
  '--dsw-alias-state-success-primary': '#82D29A',
  '--dsw-alias-state-success-secondary': '#9BDEAC',
  '--dsw-alias-state-success-tertiary': '#173722',
  '--dsw-alias-state-warn-label': '#E9BD68',
  '--dsw-alias-state-warn-primary': '#E9BD68',
  '--dsw-alias-state-warn-secondary': '#F2CC82',
  '--dsw-alias-state-warn-tertiary': '#3A2D14',

  '--dsw-alias-toast-bg': '#193333',
  '--dsw-alias-tooltip-bg': '#193333',
  '--dsw-specific-bubble': 'rgb(15 32 34 / 94%)',
  '--dsw-specific-bubble-highlight': '#193333',
  '--dsw-specific-input-major': 'rgb(15 32 34 / 94%)',
  '--dsw-specific-login-input': 'rgb(11 24 27 / 92%)',
  '--dsw-specific-menu': '#142A2A',
  '--dsw-specific-selector': '#193333',
  '--dsw-specific-sidebar-fill': 'rgb(7 20 24 / 50%)',
  '--dsw-specific-sidebar-nav-item-active-accent': '#244A45',
  '--dsw-specific-sidebar-nav-item-active': '#193333',
  '--dsw-specific-sidebar-nav-item-hover': '#0F2022',
  '--dsw-specific-tip': '#142A2A',
}

/** Inspectable light theme definition for Xiaohei Dawn. */
export const XIAOHEI_DAWN_THEME = {
  id: XIAOHEI_DAWN_THEME_ID,
  colorScheme: 'light',
  tokens: DAWN_TOKENS,
} satisfies ThemeDefinition

/** Inspectable dark theme definition for Xiaohei Night. */
export const XIAOHEI_NIGHT_THEME = {
  id: XIAOHEI_NIGHT_THEME_ID,
  colorScheme: 'dark',
  tokens: NIGHT_TOKENS,
} satisfies ThemeDefinition

/** DSH's native Light / Dark / System preference stays authoritative. */
export const XIAOHEI_THEME_TOKEN_OVERRIDES = Object.fromEntries(
  [...new Set([...Object.keys(DAWN_TOKENS), ...Object.keys(NIGHT_TOKENS)])].map(name => [
    name,
    {
      light: DAWN_TOKENS[name] ?? NIGHT_TOKENS[name],
      dark: NIGHT_TOKENS[name] ?? DAWN_TOKENS[name],
    },
  ]),
) as ThemeTokenOverrides
