import type {
  ThemeDefinition,
  ThemeTokenOverrides,
  ThemeTokens,
} from '@deepseek-ai/dsh-client-ui-theme/client'

/** Stable ids retained for consumers that inspect the two Xiaohei palettes. */
export const XIAOHEI_DAWN_THEME_ID = 'xiaohei-dawn'
export const XIAOHEI_NIGHT_THEME_ID = 'xiaohei-night'

const DAWN_TOKENS: ThemeTokens = {
  '--dsw-alias-bg-base': 'rgb(239 243 238 / 18%)',
  '--dsw-alias-bg-layer-1': 'rgb(249 251 248 / 72%)',
  '--dsw-alias-bg-layer-2': 'rgb(247 250 247 / 88%)',
  '--dsw-alias-bg-layer-3': 'rgb(242 247 243 / 95%)',
  '--dsw-alias-bg-overlay': '#F7FAF7',
  '--dsw-alias-bg-module-platform': 'rgb(246 249 246 / 84%)',
  '--dsw-alias-bg-multi-select': '#E8F0EA',
  '--dsw-alias-bg-skeleton': 'rgb(45 116 136 / 10%)',

  '--dsw-alias-border-inverted2': 'rgb(38 99 116 / 6%)',
  '--dsw-alias-border-inverted': 'rgb(38 99 116 / 9%)',
  '--dsw-alias-border-l1': 'rgb(38 99 116 / 9%)',
  '--dsw-alias-border-l2-darkmode-thin': 'rgb(38 99 116 / 12%)',
  '--dsw-alias-border-l2': 'rgb(38 99 116 / 15%)',
  '--dsw-alias-border-l3': 'rgb(38 99 116 / 22%)',
  '--dsw-alias-border-l4': 'rgb(38 99 116 / 31%)',

  '--dsw-alias-brand-primary': '#2E747A',
  '--dsw-alias-brand-primary-invert': '#F7FBF8',
  '--dsw-alias-brand-primary-new-colorprimary-new-color': '#2E747A',
  '--dsw-alias-brand-text': '#285F65',
  '--dsw-alias-button-contrast-fill': '#17272B',
  '--dsw-alias-button-primary-fill': '#2E747A',
  '--dsw-alias-button-primary-hover': '#285F65',
  '--dsw-alias-button-primary-dimmed': '#9BBFBE',
  '--dsw-alias-button-elevated-fill': '#F6F9F6',
  '--dsw-alias-button-floating-fill': '#ECF2F2',
  '--dsw-alias-button-floating-hover': '#E1EBED',
  '--dsw-alias-button-ghost-active-border': '#78A7B3',
  '--dsw-alias-button-ghost-active-fill': 'rgb(45 116 136 / 12%)',
  '--dsw-alias-button-ghost-active-hover': 'rgb(45 116 136 / 18%)',
  '--dsw-alias-button-info-fill': '#2E747A',
  '--dsw-alias-button-info-hover': '#285F65',

  '--dsw-alias-interactive-bg-active': 'rgb(45 116 136 / 15%)',
  '--dsw-alias-interactive-bg-hover-accent': 'rgb(45 116 136 / 18%)',
  '--dsw-alias-interactive-bg-hover-solid': '#E7EFF0',
  '--dsw-alias-interactive-bg-hover': 'rgb(45 116 136 / 9%)',

  '--dsw-alias-label-primary': '#17272B',
  '--dsw-alias-label-primary-bluish': '#17272B',
  '--dsw-alias-label-primary-dimmed': '#33474C',
  '--dsw-alias-label-primary-foreground': '#FFFFFF',
  '--dsw-alias-label-primary-inverted': '#F7FAF7',
  '--dsw-alias-label-secondary': '#4F646A',
  '--dsw-alias-label-tertiary': '#5E7277',
  '--dsw-alias-label-caption': '#5F7176',
  '--dsw-alias-label-dimmed': '#879598',

  '--dsw-alias-markdown-citation': '#E4EDE7',
  '--dsw-alias-markdown-code-block-banner': '#E7EEE9',
  '--dsw-alias-markdown-code-block': '#F2F6F3',
  '--dsw-alias-markdown-code-segment-selected': '#DDE8E1',
  '--dsw-alias-markdown-code-segment-unselected': '#EDF3EF',
  '--dsw-alias-markdown-inline-code': '#E8F0EA',
  '--dsw-alias-markdown-placeholder': '#EDF3EF',
  '--dsw-alias-markdown-tag': '#E4EDE7',

  '--dsw-alias-scrollbar-bg-l1': '#C7D4CD',
  '--dsw-alias-scrollbar-bg-l2': '#B7C8BF',
  '--dsw-alias-scrollbar-hover-l1': '#A5BAB0',
  '--dsw-alias-scrollbar-hover-l2': '#91AA9F',

  '--dsw-alias-state-error-primary': '#B44952',
  '--dsw-alias-state-error-secondary': '#C65D65',
  '--dsw-alias-state-business-primary': '#2E747A',
  '--dsw-alias-state-business-tertiary': '#DCE9EC',
  '--dsw-alias-state-success-primary': '#2F7B52',
  '--dsw-alias-state-success-secondary': '#438D65',
  '--dsw-alias-state-success-tertiary': '#DCEBDF',
  '--dsw-alias-state-warn-label': '#8A5B1C',
  '--dsw-alias-state-warn-primary': '#9A6720',
  '--dsw-alias-state-warn-secondary': '#AD7A34',
  '--dsw-alias-state-warn-tertiary': '#F3E8D2',

  '--dsw-alias-toast-bg': '#F7FAF7',
  '--dsw-alias-tooltip-bg': '#25332F',
  '--dsw-specific-bubble': 'rgb(249 251 248 / 94%)',
  '--dsw-specific-bubble-highlight': '#E8F0EA',
  '--dsw-specific-input-major': 'rgb(250 252 249 / 94%)',
  '--dsw-specific-login-input': 'rgb(247 250 247 / 94%)',
  '--dsw-specific-menu': '#F4F8F4',
  '--dsw-specific-selector': '#E8F0EA',
  '--dsw-specific-sidebar-fill': 'rgb(239 245 240 / 76%)',
  '--dsw-specific-sidebar-nav-item-active-accent': '#CEE0E4',
  '--dsw-specific-sidebar-nav-item-active': '#E2ECEE',
  '--dsw-specific-sidebar-nav-item-hover': '#EAF1F1',
  '--dsw-specific-tip': '#E8F0EA',
}

const NIGHT_TOKENS: ThemeTokens = {
  '--dsw-alias-bg-base': 'rgb(8 22 28 / 14%)',
  '--dsw-alias-bg-layer-1': 'rgb(11 27 34 / 70%)',
  '--dsw-alias-bg-layer-2': 'rgb(15 35 42 / 84%)',
  '--dsw-alias-bg-layer-3': 'rgb(20 44 51 / 92%)',
  '--dsw-alias-bg-overlay': '#192F38',
  '--dsw-alias-bg-module-platform': 'rgb(10 25 32 / 76%)',
  '--dsw-alias-bg-multi-select': '#142D34',
  '--dsw-alias-bg-skeleton': 'rgb(99 193 199 / 9%)',

  '--dsw-alias-border-inverted2': 'rgb(126 210 225 / 7%)',
  '--dsw-alias-border-inverted': 'rgb(126 210 225 / 10%)',
  '--dsw-alias-border-l1': 'rgb(126 210 225 / 8%)',
  '--dsw-alias-border-l2-darkmode-thin': 'rgb(126 210 225 / 11%)',
  '--dsw-alias-border-l2': 'rgb(126 210 225 / 15%)',
  '--dsw-alias-border-l3': 'rgb(126 210 225 / 23%)',
  '--dsw-alias-border-l4': 'rgb(126 210 225 / 32%)',

  '--dsw-alias-brand-primary': '#63C1C7',
  '--dsw-alias-brand-primary-invert': '#071A20',
  '--dsw-alias-brand-primary-new-colorprimary-new-color': '#63C1C7',
  '--dsw-alias-brand-text': '#7DD5D9',
  '--dsw-alias-button-contrast-fill': '#E7F3F0',
  '--dsw-alias-button-primary-fill': '#63C1C7',
  '--dsw-alias-button-primary-hover': '#7DD5D9',
  '--dsw-alias-button-primary-dimmed': '#376E73',
  '--dsw-alias-button-elevated-fill': '#192F38',
  '--dsw-alias-button-floating-fill': '#142D34',
  '--dsw-alias-button-floating-hover': '#1E3C43',
  '--dsw-alias-button-ghost-active-border': '#376E73',
  '--dsw-alias-button-ghost-active-fill': 'rgb(99 193 199 / 16%)',
  '--dsw-alias-button-ghost-active-hover': 'rgb(99 193 199 / 23%)',
  '--dsw-alias-button-info-fill': '#63C1C7',
  '--dsw-alias-button-info-hover': '#7DD5D9',

  '--dsw-alias-interactive-bg-active': 'rgb(99 193 199 / 18%)',
  '--dsw-alias-interactive-bg-hover-accent': 'rgb(99 193 199 / 24%)',
  '--dsw-alias-interactive-bg-hover-solid': '#192F38',
  '--dsw-alias-interactive-bg-hover': 'rgb(99 193 199 / 10%)',

  '--dsw-alias-label-primary': '#E8F2F4',
  '--dsw-alias-label-primary-bluish': '#E8F2F4',
  '--dsw-alias-label-primary-dimmed': '#CEDDE0',
  '--dsw-alias-label-primary-foreground': '#071A20',
  '--dsw-alias-label-primary-inverted': '#192F38',
  '--dsw-alias-label-secondary': '#B7CDD1',
  '--dsw-alias-label-tertiary': '#90A8AD',
  '--dsw-alias-label-caption': '#80999E',
  '--dsw-alias-label-dimmed': '#61777C',

  '--dsw-alias-markdown-citation': '#192F38',
  '--dsw-alias-markdown-code-block-banner': '#0F2022',
  '--dsw-alias-markdown-code-block': '#071114',
  '--dsw-alias-markdown-code-segment-selected': '#192F38',
  '--dsw-alias-markdown-code-segment-unselected': '#0B181B',
  '--dsw-alias-markdown-inline-code': '#142D34',
  '--dsw-alias-markdown-placeholder': '#0F2022',
  '--dsw-alias-markdown-tag': '#142D34',

  '--dsw-alias-scrollbar-bg-l1': '#294A47',
  '--dsw-alias-scrollbar-bg-l2': '#35605B',
  '--dsw-alias-scrollbar-hover-l1': '#42746D',
  '--dsw-alias-scrollbar-hover-l2': '#4E877E',

  '--dsw-alias-state-error-primary': '#FF7D86',
  '--dsw-alias-state-error-secondary': '#FF9AA1',
  '--dsw-alias-state-business-primary': '#63C1C7',
  '--dsw-alias-state-business-tertiary': '#192F38',
  '--dsw-alias-state-success-primary': '#82D29A',
  '--dsw-alias-state-success-secondary': '#9BDEAC',
  '--dsw-alias-state-success-tertiary': '#173722',
  '--dsw-alias-state-warn-label': '#E9BD68',
  '--dsw-alias-state-warn-primary': '#E9BD68',
  '--dsw-alias-state-warn-secondary': '#F2CC82',
  '--dsw-alias-state-warn-tertiary': '#3A2D14',

  '--dsw-alias-toast-bg': '#192F38',
  '--dsw-alias-tooltip-bg': '#192F38',
  '--dsw-specific-bubble': 'rgb(15 35 42 / 94%)',
  '--dsw-specific-bubble-highlight': '#192F38',
  '--dsw-specific-input-major': 'rgb(15 35 42 / 94%)',
  '--dsw-specific-login-input': 'rgb(11 27 34 / 92%)',
  '--dsw-specific-menu': '#142D34',
  '--dsw-specific-selector': '#192F38',
  '--dsw-specific-sidebar-fill': 'rgb(7 23 29 / 50%)',
  '--dsw-specific-sidebar-nav-item-active-accent': '#244A50',
  '--dsw-specific-sidebar-nav-item-active': '#192F38',
  '--dsw-specific-sidebar-nav-item-hover': '#0F2229',
  '--dsw-specific-tip': '#142D34',
}

/** Inspectable light theme definition for Xiaohei Dawn. */
export const XIAOHEI_DAWN_THEME = {
  id: XIAOHEI_DAWN_THEME_ID,
  colorScheme: 'light',
  tokens: DAWN_TOKENS,
} satisfies ThemeDefinition

/** Inspectable dark theme definition for Xiaohei Night. */
export const XIAOHEI_NIGHT_THEME = {
  id: XIAOHEI_NIGHT_THEME_ID,
  colorScheme: 'dark',
  tokens: NIGHT_TOKENS,
} satisfies ThemeDefinition

/** DSH's native Light / Dark / System preference stays authoritative. */
export const XIAOHEI_THEME_TOKEN_OVERRIDES = Object.fromEntries(
  [...new Set([...Object.keys(DAWN_TOKENS), ...Object.keys(NIGHT_TOKENS)])].map(name => [
    name,
    {
      light: DAWN_TOKENS[name] ?? NIGHT_TOKENS[name],
      dark: NIGHT_TOKENS[name] ?? DAWN_TOKENS[name],
    },
  ]),
) as ThemeTokenOverrides
