import type {
  ThemeDefinition,
  ThemeTokenOverrides,
  ThemeTokens,
} from '@deepseek-ai/dsh-client-ui-theme/client'

/** Stable ids retained for consumers that inspect the two Xiaohei palettes. */
export const XIAOHEI_DAWN_THEME_ID = 'xiaohei-dawn'
export const XIAOHEI_NIGHT_THEME_ID = 'xiaohei-night'

const DAWN_TOKENS: ThemeTokens = {
  '--dsw-alias-bg-base': 'rgb(238 239 235 / 18%)',
  '--dsw-alias-bg-layer-1': 'rgb(249 249 245 / 72%)',
  '--dsw-alias-bg-layer-2': 'rgb(247 247 244 / 88%)',
  '--dsw-alias-bg-layer-3': 'rgb(242 243 239 / 95%)',
  '--dsw-alias-bg-overlay': '#F5F5F1',
  '--dsw-alias-bg-module-platform': 'rgb(246 246 242 / 84%)',
  '--dsw-alias-bg-multi-select': '#E8E9E5',
  '--dsw-alias-bg-skeleton': 'rgb(45 116 136 / 10%)',

  '--dsw-alias-border-inverted2': 'rgb(35 50 52 / 6%)',
  '--dsw-alias-border-inverted': 'rgb(35 50 52 / 9%)',
  '--dsw-alias-border-l1': 'rgb(35 50 52 / 9%)',
  '--dsw-alias-border-l2-darkmode-thin': 'rgb(35 50 52 / 12%)',
  '--dsw-alias-border-l2': 'rgb(35 50 52 / 15%)',
  '--dsw-alias-border-l3': 'rgb(35 50 52 / 22%)',
  '--dsw-alias-border-l4': 'rgb(35 50 52 / 31%)',

  '--dsw-alias-brand-primary': '#2E747A',
  '--dsw-alias-brand-primary-invert': '#F8F8F4',
  '--dsw-alias-brand-primary-new-colorprimary-new-color': '#2E747A',
  '--dsw-alias-brand-text': '#285F65',
  '--dsw-alias-button-contrast-fill': '#17272B',
  '--dsw-alias-button-primary-fill': '#2E747A',
  '--dsw-alias-button-primary-hover': '#285F65',
  '--dsw-alias-button-primary-dimmed': '#9BBFBE',
  '--dsw-alias-button-elevated-fill': '#F7F7F3',
  '--dsw-alias-button-floating-fill': '#EDEEEA',
  '--dsw-alias-button-floating-hover': '#E2E5E2',
  '--dsw-alias-button-ghost-active-border': '#78A7B3',
  '--dsw-alias-button-ghost-active-fill': 'rgb(45 116 136 / 12%)',
  '--dsw-alias-button-ghost-active-hover': 'rgb(45 116 136 / 18%)',
  '--dsw-alias-button-info-fill': '#2E747A',
  '--dsw-alias-button-info-hover': '#285F65',

  '--dsw-alias-interactive-bg-active': 'rgb(45 116 136 / 15%)',
  '--dsw-alias-interactive-bg-hover-accent': 'rgb(45 116 136 / 18%)',
  '--dsw-alias-interactive-bg-hover-solid': '#E5E9E7',
  '--dsw-alias-interactive-bg-hover': 'rgb(45 116 136 / 9%)',

  '--dsw-alias-label-primary': '#1A2527',
  '--dsw-alias-label-primary-bluish': '#1A2527',
  '--dsw-alias-label-primary-dimmed': '#394649',
  '--dsw-alias-label-primary-foreground': '#FFFFFF',
  '--dsw-alias-label-primary-inverted': '#F5F5F1',
  '--dsw-alias-label-secondary': '#526064',
  '--dsw-alias-label-tertiary': '#626F72',
  '--dsw-alias-label-caption': '#657174',
  '--dsw-alias-label-dimmed': '#8B9495',

  '--dsw-alias-markdown-citation': '#E6E7E3',
  '--dsw-alias-markdown-code-block-banner': '#E9EAE6',
  '--dsw-alias-markdown-code-block': '#F2F3EF',
  '--dsw-alias-markdown-code-segment-selected': '#DEE1DD',
  '--dsw-alias-markdown-code-segment-unselected': '#EDEEEA',
  '--dsw-alias-markdown-inline-code': '#E8E9E5',
  '--dsw-alias-markdown-placeholder': '#EDEEEA',
  '--dsw-alias-markdown-tag': '#E6E7E3',

  '--dsw-alias-scrollbar-bg-l1': '#CBCDC9',
  '--dsw-alias-scrollbar-bg-l2': '#BABDBA',
  '--dsw-alias-scrollbar-hover-l1': '#A8ADAA',
  '--dsw-alias-scrollbar-hover-l2': '#959C98',

  '--dsw-alias-state-error-primary': '#B44952',
  '--dsw-alias-state-error-secondary': '#C65D65',
  '--dsw-alias-state-business-primary': '#2E747A',
  '--dsw-alias-state-business-tertiary': '#DCE9EC',
  '--dsw-alias-state-success-primary': '#2F7B52',
  '--dsw-alias-state-success-secondary': '#438D65',
  '--dsw-alias-state-success-tertiary': '#DCEBDF',
  '--dsw-alias-state-warn-label': '#8A5B1C',
  '--dsw-alias-state-warn-primary': '#9A6720',
  '--dsw-alias-state-warn-secondary': '#AD7A34',
  '--dsw-alias-state-warn-tertiary': '#F3E8D2',

  '--dsw-alias-toast-bg': '#F5F5F1',
  '--dsw-alias-tooltip-bg': '#25332F',
  '--dsw-specific-bubble': 'rgb(249 249 245 / 94%)',
  '--dsw-specific-bubble-highlight': '#E8E9E5',
  '--dsw-specific-input-major': 'rgb(251 251 248 / 94%)',
  '--dsw-specific-login-input': 'rgb(247 247 244 / 94%)',
  '--dsw-specific-menu': '#F4F4F0',
  '--dsw-specific-selector': '#E8E9E5',
  '--dsw-specific-sidebar-fill': 'rgb(239 240 236 / 76%)',
  '--dsw-specific-sidebar-nav-item-active-accent': '#CEE0E4',
  '--dsw-specific-sidebar-nav-item-active': '#E2ECEE',
  '--dsw-specific-sidebar-nav-item-hover': '#EAF1F1',
  '--dsw-specific-tip': '#E8E9E5',
}

const NIGHT_TOKENS: ThemeTokens = {
  '--dsw-alias-bg-base': 'rgb(8 11 12 / 14%)',
  '--dsw-alias-bg-layer-1': 'rgb(13 18 19 / 70%)',
  '--dsw-alias-bg-layer-2': 'rgb(19 25 26 / 84%)',
  '--dsw-alias-bg-layer-3': 'rgb(25 32 33 / 92%)',
  '--dsw-alias-bg-overlay': '#1D2627',
  '--dsw-alias-bg-module-platform': 'rgb(11 16 17 / 76%)',
  '--dsw-alias-bg-multi-select': '#182123',
  '--dsw-alias-bg-skeleton': 'rgb(99 193 199 / 9%)',

  '--dsw-alias-border-inverted2': 'rgb(184 204 205 / 7%)',
  '--dsw-alias-border-inverted': 'rgb(184 204 205 / 10%)',
  '--dsw-alias-border-l1': 'rgb(184 204 205 / 8%)',
  '--dsw-alias-border-l2-darkmode-thin': 'rgb(184 204 205 / 11%)',
  '--dsw-alias-border-l2': 'rgb(184 204 205 / 15%)',
  '--dsw-alias-border-l3': 'rgb(184 204 205 / 23%)',
  '--dsw-alias-border-l4': 'rgb(184 204 205 / 32%)',

  '--dsw-alias-brand-primary': '#63C1C7',
  '--dsw-alias-brand-primary-invert': '#091112',
  '--dsw-alias-brand-primary-new-colorprimary-new-color': '#63C1C7',
  '--dsw-alias-brand-text': '#7DD5D9',
  '--dsw-alias-button-contrast-fill': '#E7F3F0',
  '--dsw-alias-button-primary-fill': '#63C1C7',
  '--dsw-alias-button-primary-hover': '#7DD5D9',
  '--dsw-alias-button-primary-dimmed': '#376E73',
  '--dsw-alias-button-elevated-fill': '#1D2627',
  '--dsw-alias-button-floating-fill': '#182123',
  '--dsw-alias-button-floating-hover': '#253132',
  '--dsw-alias-button-ghost-active-border': '#376E73',
  '--dsw-alias-button-ghost-active-fill': 'rgb(99 193 199 / 16%)',
  '--dsw-alias-button-ghost-active-hover': 'rgb(99 193 199 / 23%)',
  '--dsw-alias-button-info-fill': '#63C1C7',
  '--dsw-alias-button-info-hover': '#7DD5D9',

  '--dsw-alias-interactive-bg-active': 'rgb(99 193 199 / 18%)',
  '--dsw-alias-interactive-bg-hover-accent': 'rgb(99 193 199 / 24%)',
  '--dsw-alias-interactive-bg-hover-solid': '#1D2627',
  '--dsw-alias-interactive-bg-hover': 'rgb(99 193 199 / 10%)',

  '--dsw-alias-label-primary': '#E8F2F4',
  '--dsw-alias-label-primary-bluish': '#E8F2F4',
  '--dsw-alias-label-primary-dimmed': '#CEDDE0',
  '--dsw-alias-label-primary-foreground': '#091112',
  '--dsw-alias-label-primary-inverted': '#1D2627',
  '--dsw-alias-label-secondary': '#B7CDD1',
  '--dsw-alias-label-tertiary': '#90A8AD',
  '--dsw-alias-label-caption': '#80999E',
  '--dsw-alias-label-dimmed': '#61777C',

  '--dsw-alias-markdown-citation': '#1D2627',
  '--dsw-alias-markdown-code-block-banner': '#111718',
  '--dsw-alias-markdown-code-block': '#090D0E',
  '--dsw-alias-markdown-code-segment-selected': '#1D2627',
  '--dsw-alias-markdown-code-segment-unselected': '#0D1314',
  '--dsw-alias-markdown-inline-code': '#182123',
  '--dsw-alias-markdown-placeholder': '#111718',
  '--dsw-alias-markdown-tag': '#182123',

  '--dsw-alias-scrollbar-bg-l1': '#303A3A',
  '--dsw-alias-scrollbar-bg-l2': '#3C4747',
  '--dsw-alias-scrollbar-hover-l1': '#4B5857',
  '--dsw-alias-scrollbar-hover-l2': '#5A6867',

  '--dsw-alias-state-error-primary': '#FF7D86',
  '--dsw-alias-state-error-secondary': '#FF9AA1',
  '--dsw-alias-state-business-primary': '#63C1C7',
  '--dsw-alias-state-business-tertiary': '#1D2627',
  '--dsw-alias-state-success-primary': '#82D29A',
  '--dsw-alias-state-success-secondary': '#9BDEAC',
  '--dsw-alias-state-success-tertiary': '#173722',
  '--dsw-alias-state-warn-label': '#E9BD68',
  '--dsw-alias-state-warn-primary': '#E9BD68',
  '--dsw-alias-state-warn-secondary': '#F2CC82',
  '--dsw-alias-state-warn-tertiary': '#3A2D14',

  '--dsw-alias-toast-bg': '#1D2627',
  '--dsw-alias-tooltip-bg': '#1D2627',
  '--dsw-specific-bubble': 'rgb(19 25 26 / 94%)',
  '--dsw-specific-bubble-highlight': '#1D2627',
  '--dsw-specific-input-major': 'rgb(19 25 26 / 94%)',
  '--dsw-specific-login-input': 'rgb(13 18 19 / 92%)',
  '--dsw-specific-menu': '#182123',
  '--dsw-specific-selector': '#1D2627',
  '--dsw-specific-sidebar-fill': 'rgb(8 13 14 / 50%)',
  '--dsw-specific-sidebar-nav-item-active-accent': '#25484B',
  '--dsw-specific-sidebar-nav-item-active': '#1D292A',
  '--dsw-specific-sidebar-nav-item-hover': '#151D1E',
  '--dsw-specific-tip': '#182123',
}

/** Inspectable light theme definition for Xiaohei Dawn. */
export const XIAOHEI_DAWN_THEME = {
  id: XIAOHEI_DAWN_THEME_ID,
  colorScheme: 'light',
  tokens: DAWN_TOKENS,
} satisfies ThemeDefinition

/** Inspectable dark theme definition for Xiaohei Night. */
export const XIAOHEI_NIGHT_THEME = {
  id: XIAOHEI_NIGHT_THEME_ID,
  colorScheme: 'dark',
  tokens: NIGHT_TOKENS,
} satisfies ThemeDefinition

/** DSH's native Light / Dark / System preference stays authoritative. */
export const XIAOHEI_THEME_TOKEN_OVERRIDES = Object.fromEntries(
  [...new Set([...Object.keys(DAWN_TOKENS), ...Object.keys(NIGHT_TOKENS)])].map(name => [
    name,
    {
      light: DAWN_TOKENS[name] ?? NIGHT_TOKENS[name],
      dark: NIGHT_TOKENS[name] ?? DAWN_TOKENS[name],
    },
  ]),
) as ThemeTokenOverrides
